// ════════════════════════════════════════════════════════════════
// LegitUI — Component Registry (Metadata Only)
// ════════════════════════════════════════════════════════════════
// Phase 2 ✔✔ Phase 3 Refactor:
//  — All code strings removed (Phase 2). Source code read from disk at request-time.
//  — Types now imported from registry-types.ts (single source of truth).
// ════════════════════════════════════════════════════════════════

// Import types from the single source of truth
import type { ComponentRegistryEntry, ComponentProp } from './registry-types';
export type { ComponentRegistryEntry, ComponentProp };

// Re-export under the legacy name so consumers don't need to change imports
export type ComponentMeta = ComponentRegistryEntry;

export interface Category {
  name: string;
  slug: string;
  icon?: string;
}

export const categories: Category[] = [
  { name: "Animations", slug: "animations" },
  { name: "TextAnimations", slug: "textanimations" },
  { name: "Backgrounds", slug: "backgrounds" },
  { name: "LegitComponents", slug: "legitcomponents" },
  { name: "Buttons", slug: "buttons" },
  { name: "Cards", slug: "cards" },
  { name: "Text Effects", slug: "text-effects" },
  { name: "Inputs", slug: "inputs" },
  { name: "Loaders", slug: "loaders" },
  { name: "Navigation", slug: "navigation" },
];

// ────────────────────────────────────────────────────
// Default seed components — METADATA ONLY
// ────────────────────────────────────────────────────
export const defaultComponents: ComponentMeta[] = [
  {
    id: "1",
    name: "Shimmer Button",
    slug: "shimmer-button",
    folder: "ShimmerButton",
    fileName: "ShimmerButton",
    category: "Buttons",
    description: "A button with a beautiful shimmer animation effect that catches the eye. Perfect for CTAs and primary actions.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Button content" },
      { name: "onClick", type: "() => void", description: "Click handler" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
      { name: "background", type: "string", default: '"linear-gradient(135deg, #FF0080, #7928CA)"', description: "Button background" },
      { name: "shimmerColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Shimmer line color" },
      { name: "shimmerDuration", type: "string", default: '"2s"', description: "Shimmer animation duration" },
      { name: "borderRadius", type: "string", default: '"10px"', description: "Border radius" },
    ],
    tags: ["button", "shimmer", "animation", "cta"],
    isNew: true,
    createdAt: "2024-01-15",
    previewVideo: "/sample.mp4",
  },
  {
    id: "2",
    name: "Glow Card",
    slug: "glow-card",
    folder: "GlowCard",
    fileName: "GlowCard",
    category: "Cards",
    description: "A card component with a dynamic glow effect that follows the mouse cursor. Creates an interactive and premium feel.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Card content" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
      { name: "glowColor", type: "string", default: '"168, 85, 247"', description: "Glow color" },
      { name: "backgroundColor", type: "string", default: '"#16161a"', description: "Card background color" },
      { name: "borderColor", type: "string", default: '"#27272a"', description: "Card border color" },
      { name: "borderRadius", type: "string", default: '"16px"', description: "Card border radius" },
    ],
    tags: ["card", "glow", "interactive", "hover"],
    createdAt: "2024-01-14",
    previewVideo: "/sample.mp4",
  },
  {
    id: "4",
    name: "Pulse Loader",
    slug: "pulse-loader",
    folder: "PulseLoader",
    fileName: "PulseLoader",
    category: "Loaders",
    description: "A smooth, elegant pulsing loader animation with customizable size and color.",
    props: [
      { name: "size", type: "number", default: "12", description: "Dot size in pixels" },
      { name: "color", type: "string", default: '"#a855f7"', description: "Dot color" },
      { name: "count", type: "number", default: "3", description: "Number of dots" },
      { name: "speed", type: "number", default: "1.4", description: "Animation duration in seconds" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["loader", "spinner", "animation", "loading"],
    createdAt: "2024-01-13",
  },
  {
    id: "5",
    name: "Typewriter Text",
    slug: "typewriter-text",
    folder: "TypewriterText",
    fileName: "TypewriterText",
    category: "Text Effects",
    description: "A typewriter effect that types out text character by character with a blinking cursor.",
    props: [
      { name: "text", type: "string", description: "Text to type out" },
      { name: "speed", type: "number", default: "50", description: "Typing speed in ms" },
      { name: "delay", type: "number", default: "0", description: "Delay before typing starts (ms)" },
      { name: "cursor", type: "boolean", default: "true", description: "Show blinking cursor" },
    ],
    tags: ["text", "typewriter", "animation", "typing"],
    createdAt: "2024-01-11",
  },
  {
    id: "6",
    name: "Animated Border",
    slug: "animated-border",
    folder: "AnimatedBorder",
    fileName: "AnimatedBorder",
    category: "Animations",
    description: "A container with an animated gradient border that rotates continuously. Perfect for highlighting important content.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Content inside the border" },
      { name: "borderWidth", type: "number", default: "2", description: "Border thickness in pixels" },
      { name: "speed", type: "number", default: "3", description: "Rotation speed in seconds" },
      { name: "color1", type: "string", default: '"#7c3aed"', description: "Gradient color 1" },
      { name: "color2", type: "string", default: '"#a855f7"', description: "Gradient color 2" },
      { name: "color3", type: "string", default: '"#c084fc"', description: "Gradient color 3" },
      { name: "innerColor", type: "string", default: '"#16161a"', description: "Inner background color" },
      { name: "glow", type: "boolean", default: "true", description: "Enable outer neon glow effect" },
      { name: "borderRadius", type: "number", default: "16", description: "Corner radius in pixels" },
    ],
    tags: ["border", "animation", "gradient", "container"],
    isNew: true,
    createdAt: "2024-01-15",
  },
  {
    id: "7",
    name: "Floating Input",
    slug: "floating-input",
    folder: "FloatingInput",
    fileName: "FloatingInput",
    category: "Inputs",
    description: "A text input with a floating label that animates up when focused or filled. Clean material-design inspired interaction.",
    props: [
      { name: "label", type: "string", description: "Floating label text" },
      { name: "type", type: "string", default: '"text"', description: "Input type" },
      { name: "value", type: "string", description: "Controlled value" },
      { name: "onChange", type: "(value: string) => void", description: "Change handler" },
      { name: "backgroundColor", type: "string", default: '"#111114"', description: "Background color" },
      { name: "borderColor", type: "string", default: '"#27272a"', description: "Border color" },
      { name: "focusColor", type: "string", default: '"#a855f7"', description: "Focus color" },
      { name: "textColor", type: "string", default: '"#fafafa"', description: "Text color" },
      { name: "labelColor", type: "string", default: '"#71717a"', description: "Label color" },
      { name: "borderRadius", type: "string", default: '"10px"', description: "Border radius" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["input", "form", "floating-label", "material"],
    createdAt: "2026-05-10",
  },
  {
    id: "8",
    name: "Aurora Background",
    slug: "aurora-background",
    folder: "AuroraBackground",
    fileName: "AuroraBackground",
    category: "Backgrounds",
    description: "A mesmerizing aurora borealis background effect with animated gradients. Use as a hero section background or page backdrop.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Content to display over the aurora" },
      { name: "intensity", type: "'subtle' | 'medium' | 'vivid'", default: '"medium"', description: "Aurora brightness" },
      { name: "color1", type: "string", default: '"124, 58, 237"', description: "Gradient color 1" },
      { name: "color2", type: "string", default: '"168, 85, 247"', description: "Gradient color 2" },
      { name: "color3", type: "string", default: '"192, 132, 252"', description: "Gradient color 3" },
      { name: "backgroundColor", type: "string", default: '"#09090b"', description: "Background color" },
    ],
    tags: ["background", "aurora", "gradient", "animated"],
    createdAt: "2024-01-09",
  },
  {
    id: "9",
    name: "Magnetic Button",
    slug: "magnetic-button",
    folder: "MagneticButton",
    fileName: "MagneticButton",
    category: "Buttons",
    description: "A button that magnetically attracts towards the cursor when hovering nearby. Creates a playful, interactive feel.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Button content" },
      { name: "onClick", type: "() => void", description: "Click handler" },
      { name: "strength", type: "number", default: "0.3", description: "Magnetic pull strength (0-1)" },
      { name: "scale", type: "number", default: "1.08", description: "Hover scale factor multiplier" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Button text color" },
      { name: "backgroundColor", type: "string", default: '"#a855f7"', description: "Button background hex color" },
      { name: "glowColor", type: "string", default: '"rgba(168, 85, 247, 0.45)"', description: "Ambient glow color when hovering" },
      { name: "borderRadius", type: "number", default: "12", description: "Button corner radius in pixels" },
    ],
    tags: ["button", "magnetic", "interactive", "hover"],
    createdAt: "2024-01-08",
  },
  {
    id: "10",
    name: "Spotlight Card",
    slug: "spotlight-card",
    folder: "SpotlightCard",
    fileName: "SpotlightCard",
    category: "Cards",
    description: "A card with a spotlight effect that follows the cursor. The spotlight reveals a subtle gradient beneath.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Card content" },
      { name: "spotlightColor", type: "string", default: '"rgba(168, 85, 247, 0.08)"', description: "Spotlight gradient color" },
      { name: "backgroundColor", type: "string", default: '"#16161a"', description: "Card background color" },
      { name: "borderColor", type: "string", default: '"#27272a"', description: "Card border color" },
      { name: "borderRadius", type: "string", default: '"16px"', description: "Card border radius" },
    ],
    tags: ["card", "spotlight", "interactive", "hover"],
    createdAt: "2024-01-07",
  },
  {
    id: "11",
    name: "Skeleton Loader",
    slug: "skeleton-loader",
    folder: "SkeletonLoader",
    fileName: "SkeletonLoader",
    category: "Loaders",
    description: "A customizable skeleton loading placeholder with a smooth shimmer animation.",
    props: [
      { name: "width", type: "string | number", default: '"100%"', description: "Element width" },
      { name: "height", type: "string | number", default: '"20px"', description: "Element height" },
      { name: "borderRadius", type: "string | number", default: '"8px"', description: "Corner radius" },
      { name: "baseColor", type: "string", default: '"#1c1c22"', description: "Base background color" },
      { name: "highlightColor", type: "string", default: '"#27272a"', description: "Highlight shimmer color" },
      { name: "speed", type: "number", default: "1.5", description: "Shimmer animation speed" },
    ],
    tags: ["skeleton", "loader", "placeholder", "loading"],
    createdAt: "2024-01-06",
  },
  {
    id: "12",
    name: "Ripple Button",
    slug: "ripple-button",
    folder: "RippleButton",
    fileName: "RippleButton",
    category: "Buttons",
    description: "A button with a material-design inspired ripple effect on click.",
    props: [
      { name: "children", type: "React.ReactNode", description: "Button content" },
      { name: "onClick", type: "() => void", description: "Click handler" },
      { name: "variant", type: "'filled' | 'outline'", default: '"filled"', description: "Button style variant" },
      { name: "backgroundColor", type: "string", default: '"#a855f7"', description: "Background base hex color" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Button text/outline hex color" },
      { name: "rippleColor", type: "string", default: '"rgba(255, 255, 255, 0.35)"', description: "Expanding ripple wave color" },
      { name: "borderRadius", type: "number", default: "12", description: "Button corner radius in pixels" },
      { name: "duration", type: "number", default: "0.6", description: "Ripple expansion duration in seconds" },
    ],
    tags: ["button", "ripple", "material", "click"],
    createdAt: "2024-01-05",
  },
  {
    id: "13",
    name: "Particles Background",
    slug: "particles-background",
    folder: "Particles",
    fileName: "SpaceParticles",
    category: "Backgrounds",
    description: "A mesmerizing WebGL particle field powered by OGL. Features twinkling star-like particles with customizable colors, speed, and cursor interactivity.",
    dependencies: ["ogl"],
    props: [
      { name: "particleCount", type: "number", default: "200", description: "Number of particles to render" },
      { name: "particleSpread", type: "number", default: "10", description: "How spread out the particles are" },
      { name: "speed", type: "number", default: "0.1", description: "Animation speed multiplier" },
      { name: "particleColors", type: "string[]", default: '["#ffffff", "#a855f7", "#c084fc"]', description: "Array of hex colors for particles" },
      { name: "moveParticlesOnHover", type: "boolean", default: "true", description: "Particles react to cursor movement" },
      { name: "particleHoverFactor", type: "number", default: "1.66", description: "Strength of cursor repulsion" },
      { name: "alphaParticles", type: "boolean", default: "false", description: "Enable alpha blending on particles" },
      { name: "particleBaseSize", type: "number", default: "100", description: "Base size of each particle" },
      { name: "sizeRandomness", type: "number", default: "1", description: "Randomness in particle sizes (0 = uniform)" },
      { name: "cameraDistance", type: "number", default: "20", description: "Distance of the camera from particles" },
      { name: "disableRotation", type: "boolean", default: "false", description: "Disable the slow rotation of the particle field" },
      { name: "pixelRatio", type: "number", default: "1", description: "Device pixel ratio for rendering" },
      { name: "className", type: "string", default: '""', description: "Additional CSS class name" },
    ],
    tags: ["background", "particles", "webgl", "ogl", "animation", "stars", "3d", "interactive"],
    isNew: true,
    createdAt: "2024-01-16",
  },
  {
    id: "14",
    name: "Neon Waves",
    slug: "neon-waves",
    folder: "NeonWaves",
    fileName: "NeonWaves",
    category: "Backgrounds",
    description: "A mesmerizing interactive WebGL neon ribbon background that reacts to mouse movements.",
    dependencies: ["three"],
    props: [
      { name: "lineColor1", type: "string", default: '"#ff0096"', description: "First line gradient color" },
      { name: "lineColor2", type: "string", default: '"#0066ff"', description: "Second line gradient color" },
      { name: "backgroundColor", type: "string", default: '"transparent"', description: "Background color of the container" },
      { name: "waveSpeed", type: "number", default: "1.0", description: "Speed of the wave animation" },
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
    ],
    tags: ["background", "neon", "waves", "webgl", "interactive", "3d", "three"],
    isNew: true,
    createdAt: "2024-01-16",
  },
  {
    id: "15",
    name: "Mirror Capsules",
    slug: "mirror-capsules",
    folder: "MirrorCapsules",
    fileName: "MirrorCapsule",
    category: "Backgrounds",
    description: "3D iridescent mirror capsules powered by Three.js with procedural environment mapping.",
    dependencies: ["three"],
    props: [
      { name: "width", type: "string", default: '"100%"', description: "Container width" },
      { name: "height", type: "string", default: '"100%"', description: "Container height" },
      { name: "speed", type: "number", default: "1", description: "Animation speed" },
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
    ],
    tags: ["background", "3d", "three", "webgl", "mirror", "capsules"],
    isNew: true,
    createdAt: "2024-01-16",
  },
  {
    id: "16",
    name: "Fractal Haze",
    slug: "fractal-haze",
    folder: "FractalHaze",
    fileName: "FractalHaze",
    category: "Backgrounds",
    description: "A mesmerizing organic webgl background effect simulating fluted glass refraction over a dynamic fluid gradient.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
      { name: "speed", type: "number", default: "1.8", description: "Speed of the gradient fluid animation" },
      { name: "barWidth", type: "number", default: "27.0", description: "Width of the fluted glass bars" },
      { name: "color1", type: "string", default: '"#260005"', description: "Base deep background color" },
      { name: "color2", type: "string", default: '"#ff001a"', description: "Main sweeping crimson/fluid color" },
      { name: "color3", type: "string", default: '"#fff2e5"', description: "Top right highlight color" },
      { name: "color4", type: "string", default: '"#05000c"', description: "Middle right void color" },
      { name: "color5", type: "string", default: '"#7f0005"', description: "Bottom right accent color" },
      { name: "color6", type: "string", default: '"#99ccff"', description: "Left edge highlight color" }
    ],
    tags: ["background", "webgl", "ogl", "fractal", "haze", "glass", "refraction"],
    isNew: true,
    createdAt: "2024-01-16",
  },
  {
    id: "17",
    name: "Liquid Nebula",
    slug: "liquid-nebula",
    folder: "LiquidNebula",
    fileName: "LiquidNebula",
    category: "Backgrounds",
    description: "A high-performance, fluid, and organic animated background using WebGL. Features a liquid nebula aesthetic with deep colors and interactive water ripples.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
      { name: "speed", type: "number", default: "0.35", description: "Speed of the fluid animation" },
      { name: "warpFreq", type: "number", default: "1.3", description: "Frequency of the noise warp" },
      { name: "warpAmp", type: "number", default: "0.8", description: "Amplitude of the noise warp" },
      { name: "intensity", type: "number", default: "0.65", description: "Intensity of the colors" },
      { name: "baseColor1", type: "string", default: '"#0B0F1A"', description: "First background color" },
      { name: "baseColor2", type: "string", default: '"#0F1626"', description: "Second background color" },
      { name: "color1", type: "string", default: '"#6C5CE7"', description: "Indigo fluid color" },
      { name: "color2", type: "string", default: '"#00D4FF"', description: "Cyan fluid color" },
      { name: "color3", type: "string", default: '"#FF6EC7"', description: "Pink fluid color" },
      { name: "color4", type: "string", default: '"#7B5CFF"', description: "Violet fluid color" },
      { name: "highlight", type: "string", default: '"#FFFFFF"', description: "Highlight color" },
    ],
    tags: ["background", "webgl", "ogl", "liquid", "nebula", "fluid", "interactive"],
    isNew: true,
    createdAt: "2026-04-24",
  },
  {
    id: "18",
    name: "Space Nebula V1",
    slug: "space-nebula-v1",
    folder: "SpaceNebulav1",
    fileName: "SpaceNebulav1",
    category: "Backgrounds",
    description: "A stunning volumetric space nebula simulation powered by OGL. Features deep pink and cyan flows with twinkling stars.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
      { name: "speed", type: "number", default: "1.0", description: "Speed of the flow and particle animation" },
      { name: "starCount", type: "number", default: "1200", description: "Number of stars to render" },
      { name: "warpFreq", type: "number", default: "1.0", description: "Frequency of the domain warp noise" },
      { name: "warpAmp", type: "number", default: "1.0", description: "Amplitude of the domain warp noise" },
      { name: "waveDirX", type: "number", default: "1.0", description: "Direction multiplier for magenta waves" },
      { name: "waveDirY", type: "number", default: "1.0", description: "Direction multiplier for cyan waves" },
      { name: "color1", type: "string", default: '"#ffb4f0"', description: "Primary magenta/pink color base" },
      { name: "color2", type: "string", default: '"#c8ffff"', description: "Secondary cyan/blue color base" },
      { name: "baseColor", type: "string", default: '"#03020e"', description: "Background void color" }
    ],
    tags: ["background", "webgl", "ogl", "space", "nebula", "stars", "volumetric"],
    isNew: true,
    createdAt: "2026-04-25",
  },
  {
    id: "19",
    name: "Space Nebula V2",
    slug: "space-nebula-v2",
    folder: "SpaceNebulaV2",
    fileName: "SpaceNebulaV2",
    category: "Backgrounds",
    description: "A highly dynamic, multi-layered volumetric gaseous nebula with intersecting flows and exponential ambient haze.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", default: '""', description: "Additional CSS class" },
      { name: "speed", type: "number", default: "1.0", description: "Speed of the flow and particle animation" },
      { name: "starCount", type: "number", default: "1000", description: "Number of stars to render" },
      { name: "warpFreq", type: "number", default: "1.0", description: "Frequency of the domain warp noise" },
      { name: "warpAmp", type: "number", default: "1.0", description: "Amplitude of the domain warp noise" },
      { name: "color1", type: "string", default: '"#ec4899"', description: "Primary magenta/pink color base" },
      { name: "color2", type: "string", default: '"#6366f1"', description: "Secondary cyan/blue color base" },
      { name: "baseColor", type: "string", default: '"#03020e"', description: "Background void color" }
    ],
    tags: ["background", "webgl", "ogl", "space", "nebula", "stars", "volumetric", "v2"],
    isNew: true,
    createdAt: "2026-04-25",
  },
  {
    id: "20",
    name: "Green Wave Ribbons",
    slug: "green-wave-ribbons",
    folder: "GreenWaveRibbons",
    fileName: "GreenWaveRibbons",
    category: "Backgrounds",
    description: "An immersive 3D ribbon terrain using WebGL. Fully customizable colors, height, and animation speed.",
    dependencies: ["ogl"],
    props: [
      { name: "containerClassName", type: "string", default: '""', description: "Additional CSS class for container" },
      { name: "ribbonCount", type: "number", default: "70.0", description: "Number of ribbons to display" },
      { name: "speed", type: "number", default: "1.0", description: "Animation speed multiplier" },
      { name: "darkColor", type: "string", default: '"#020e04"', description: "Deep shadow base color" },
      { name: "midColor", type: "string", default: '"#052e0b"', description: "Mid ribbon body color" },
      { name: "brightColor", type: "string", default: '"#0e8f1c"', description: "Lit surface color" },
      { name: "hotEdgeColor", type: "string", default: '"#19f233"', description: "Top cap glow color" },
      { name: "bgColor", type: "string", default: '"#010201"', description: "Background void color" },
      { name: "glowColor", type: "string", default: '"#031706"', description: "Background center glow color" },
      { name: "baseHeight", type: "number", default: "0.87", description: "Base floor height of the waves" }
    ],
    tags: ["background", "webgl", "ogl", "ribbons", "waves", "3d", "terrain"],
    isNew: true,
    createdAt: "2026-04-26",
  },
  {
    id: "21",
    name: "Cinematic Black Hole",
    slug: "cinematic-black-hole",
    folder: "BlackHole",
    fileName: "BlackHole",
    category: "Backgrounds",
    description: "A breathtaking, high-performance WebGL black hole simulation using React Three Fiber. Fully customizable accretion disk and stars.",
    dependencies: ["@react-three/fiber", "@react-three/drei", "@react-three/postprocessing", "three"],
    props: [
      { name: "containerClassName", type: "string", default: '""', description: "Additional CSS class for container" },
      { name: "speed", type: "number", default: "1.0", description: "Animation speed multiplier" },
      { name: "radius", type: "number", default: "0.28", description: "Radius of the event horizon" },
      { name: "starsCount", type: "number", default: "1500", description: "Number of background stars" },
      { name: "colorOuter", type: "string", default: '"#4c1d95"', description: "Deep void outer accretion color" },
      { name: "colorMid", type: "string", default: '"#a855f7"', description: "Mid accretion disk color" },
      { name: "colorInner", type: "string", default: '"#fff0ff"', description: "Inner accretion disk glow" }
    ],
    tags: ["background", "webgl", "threejs", "space", "black hole", "3d", "r3f"],
    isNew: true,
    createdAt: "2026-04-26",
  },
  {
    id: "22",
    name: "3D Gallery",
    slug: "3d-gallery",
    folder: "3DGallery",
    fileName: "3DGallery",
    category: "LegitComponents",
    description: "A stunning 3D interactive image carousel that responds to dragging. Perfect for showcasing projects or photos with depth and style.",
    dependencies: ["framer-motion"],
    props: [
      { name: "radius", type: "number", default: "320", description: "Radius of the 3D carousel ring in px" },
      { name: "cardWidth", type: "number", default: "220", description: "Width of each image card in px" },
      { name: "cardHeight", type: "number", default: "160", description: "Height of each image card in px" },
      { name: "spinSpeed", type: "number", default: "0.025", description: "Speed multiplier for auto-spin" },
      { name: "backgroundColor", type: "string", default: '"#ffffff"', description: "Background color of the gallery" },
      { name: "glowColor", type: "string", default: '"rgba(255,220,180,0.35)"', description: "Central ambient glow color" },
      { name: "textColor", type: "string", default: '"#8a7a6a"', description: "Text color for headers and hints" },
      { name: "headerText", type: "string", default: '"Gallery"', description: "Top header text" },
      { name: "centralTitle", type: "string", default: '"Projects"', description: "Large central text" },
      { name: "centralSubtitle", type: "string", default: '"Collection"', description: "Small subtitle under central text" },
    ],
    tags: ["3d", "gallery", "carousel", "framer-motion", "interactive", "images"],
    isNew: true,
    createdAt: "2026-04-26",
  },
  {
    id: "23",
    name: "Scroll Gallery",
    slug: "scroll-gallery",
    folder: "ScrollGallery",
    fileName: "ScrollGallery",
    category: "LegitComponents",
    description: "A beautifully curved, infinite scrolling 3D image gallery. Features cinematic lighting, dynamic scaling, and hover effects.",
    dependencies: ["three", "@react-three/fiber"],
    props: [
      { name: "curvature", type: "number", default: "10", description: "Radius of the cylindrical bend", min: 5, max: 20, step: 1 },
      { name: "cardWidth", type: "number", default: "2", description: "Width of each card in 3D space", min: 1, max: 5, step: 0.1 },
      { name: "cardHeight", type: "number", default: "2", description: "Height of each card in 3D space", min: 1, max: 6, step: 0.1 },
      { name: "gap", type: "number", default: "0.35", description: "Gap between cards", min: 0, max: 2, step: 0.05 },
      { name: "speed", type: "number", default: "2.5", description: "Auto-scroll speed", min: 0, max: 10, step: 0.1 },
      { name: "fov", type: "number", default: "55", description: "Camera field of view", min: 30, max: 120, step: 1 },
    ],
    tags: ["3d", "gallery", "carousel", "scroll", "threejs", "r3f", "interactive"],
    isNew: true,
    createdAt: "2026-04-26",
  },
  {
    id: "24",
    name: "Text Reveal",
    slug: "text-reveal",
    folder: "TextReveal",
    fileName: "TextReveal",
    category: "TextAnimations",
    description: "A text reveal effect that fades in characters as you scroll, creating a cinematic wipe reveal animation.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", description: "The text to reveal on scroll", default: '"Scroll to reveal this text"' },
      { name: "activeColor", type: "string", description: "Color of the text when fully revealed", default: '"#ffffff"' },
      { name: "inactiveColor", type: "string", description: "Color of the text before it is revealed", default: '"#6b7280"' },
      { name: "opacityStart", type: "number", description: "Initial opacity of the unrevealed text", default: "0.1", min: 0, max: 1, step: 0.1 },
      { name: "opacityEnd", type: "number", description: "Final opacity of the revealed text", default: "1", min: 0, max: 1, step: 0.1 },
      { name: "className", type: "string", description: "Additional CSS class for the container", default: '""' }
    ],
    tags: ["text", "reveal", "scroll", "gsap", "animation", "wipe"],
    isNew: true,
    createdAt: "2026-04-26",
  },
  {
    id: "25",
    name: "Smooth Fade Up",
    slug: "smooth-fade-up",
    folder: "SmoothFadeUp",
    fileName: "SmoothFadeUp",
    category: "TextAnimations",
    description: "A polished staggered fade-in-from-below animation — the gold-standard motion pattern for hero sections and landing pages.",
    dependencies: ["gsap"],
    props: [
      { name: "heading", type: "string", default: '"Elevate Your Experience"', description: "Main headline text" },
      { name: "subheading", type: "string", default: '"Crafted with precision. Designed for impact."', description: "Secondary tagline / subtitle" },
      { name: "description", type: "string", default: '"A smooth, staggered fade‑in…"', description: "Body paragraph" },
      { name: "badge", type: "string", default: '"✦ Introducing"', description: "Small pill / badge text above the heading" },
      { name: "distance", type: "number", default: "60", description: "Pixels the elements travel upward" },
      { name: "duration", type: "number", default: "1", description: "Seconds per element" },
      { name: "stagger", type: "number", default: "0.15", description: "Seconds between each element" },
      { name: "ease", type: "string", default: '"power3.out"', description: "GSAP ease string" },
      { name: "scrub", type: "boolean", default: "false", description: "Tie animation to scroll progress" },
    ],
    tags: ["text", "fade", "stagger", "gsap", "animation", "hero", "intro"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "26",
    name: "Cinematic Text",
    slug: "cinematic-text",
    folder: "CinematicText",
    fileName: "CinematicText",
    category: "TextAnimations",
    description: "A premium scroll-linked 3D letter animation with depth, blur, and color transitions. ",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Cinematic"', description: "Main heading text to animate" },
      { name: "subtitle", type: "string", default: '"Letter by Letter — Framer Motion"', description: "Optional subtitle appearing after letters" },
      { name: "activeColor", type: "string", default: '"#ffffff"', description: "Color of active/focused letters" },
      { name: "inactiveColor", type: "string", default: '"#1a1a2e"', description: "Base color for hidden/unfocused letters" },
      { name: "fontSize", type: "string", default: '"clamp(3rem, 10vw, 9rem)"', description: "CSS font-size for the heading" },
    ],
    tags: ["text", "3d", "framer-motion", "scroll", "animation", "cinematic", "blur"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "27",
    name: "Scale Blur",
    slug: "scale-blur",
    folder: "ScaleBlur",
    fileName: "ScaleBlur",
    category: "TextAnimations",
    description: "A premium GSAP-powered text animation featuring smooth scaling and blurring effects as words reveal on scroll.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"GSAP Scale + Blur Reveal"', description: "The text to animate" },
    ],
    tags: ["text", "gsap", "scroll", "animation", "blur", "scale"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "28",
    name: "Staggered Word Slide",
    slug: "staggered-word-slide",
    folder: "StaggeredWordSlide",
    fileName: "StaggeredWordSlide",
    category: "TextAnimations",
    description: "A premium text effect that slides words up from a mask with a staggered delay using GSAP and Framer Motion.",
    dependencies: ["gsap", "framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Elevating Digital Experiences With Premium Motion"', description: "The main text to animate" },
      { name: "subtitle", type: "string", default: '"Our bespoke animation engine delivers fluid, high-fidelity transitions that captivate users and define modern web aesthetics."', description: "The subtitle text below the main heading" },
    ],
    tags: ["text", "gsap", "framer-motion", "stagger", "slide", "reveal"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "29",
    name: "Typing Cursor",
    slug: "typing-cursor",
    folder: "TypingCursor",
    fileName: "TypingCursor",
    category: "TextAnimations",
    description: "An ultra-smooth typing effect with a glowing cursor, featuring staggered character reveals and hardware-accelerated animations.",
    dependencies: ["gsap", "framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Web Developer"', description: "The text to type out" },
      { name: "typingSpeed", type: "number", default: "0.04", description: "Delay between each character typing" },
      { name: "delay", type: "number", default: "0.5", description: "Initial delay before typing starts" },
      { name: "fontSize", type: "string", description: "CSS font size for the text" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "typing", "cursor", "gsap", "framer-motion", "animation"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "30",
    name: "Typewriter Text",
    slug: "typewriter-text-new",
    folder: "TypewriterText",
    fileName: "TypewriterText",
    category: "TextAnimations",
    description: "A classic character-by-character typewriter effect with a customizable blinking cursor.",
    dependencies: [],
    props: [
      { name: "text", type: "string", default: '"Modern Typewriter Effect"', description: "The text to type out" },
      { name: "speed", type: "number", default: "50", description: "Typing speed in milliseconds" },
      { name: "delay", type: "number", default: "0", description: "Initial delay before typing starts" },
      { name: "cursor", type: "boolean", default: "true", description: "Whether to show the blinking cursor" },
    ],
    tags: ["text", "typewriter", "classic", "animation"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "31",
    name: "Pixelify Text",
    slug: "pixelify-text",
    folder: "PixelifyText",
    fileName: "PixelifyText",
    category: "TextAnimations",
    description: "A professional pixel-style text animation. Reconstructs text from individual pixels with a high-end digital effect.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"PIXEL ART"', description: "The text to animate" },
      { name: "gridSize", type: "number", default: "4", description: "Size of each pixel in the grid" },
      { name: "color", type: "string", default: '"#FFFFFF"', description: "Color of the pixels" },
      { name: "fontSize", type: "number", default: "120", description: "Font size for the text sampling" },
      { name: "fontFamily", type: "string", default: '"Inter, system-ui, sans-serif"', description: "Font family for the text" },
      { name: "delay", type: "number", default: "0", description: "Initial delay before animation starts" },
      { name: "duration", type: "number", default: "1.5", description: "Total duration of the reveal effect" },
      { name: "stagger", type: "number", default: "0.0005", description: "Delay between each pixel's appearance" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "pixel", "animation", "gsap", "canvas", "digital"],
    isNew: true,
    createdAt: "2026-04-28",
  },
  {
    id: "32",
    name: "Numbers Count",
    slug: "numbers-count",
    folder: "NumbersCount",
    fileName: "NumbersCount",
    category: "TextAnimations",
    description: "An ultra-smooth, premium number counter featuring spring physics, motion blur, and a technical pixel-grid aesthetic.",
    dependencies: ["framer-motion"],
    props: [
      { name: "end", type: "number", default: "100", description: "The final value to count up to" },
      { name: "start", type: "number", default: "0", description: "The starting value" },
      { name: "suffix", type: "string", default: '""', description: "Optional suffix (e.g., %, K, GB)" },
      { name: "decimals", type: "number", default: "0", description: "Number of decimal places to show" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "numbers", "counter", "framer-motion", "animation", "spring", "technical"],
    isNew: true,
    createdAt: "2026-04-29",
  },
  {
    id: "34",
    name: "Animated Gradient Text",
    slug: "animated-gradient-text",
    folder: "AnimatedGradient",
    fileName: "AnimatedGradient",
    category: "TextAnimations",
    description: "A premium, Apple-style animated gradient text component with a continuous color-shifting effect powered by Framer Motion.",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Beautifully Crafted"', description: "The text to display" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "gradient", "animation", "framer-motion", "apple", "premium"],
    isNew: true,
    createdAt: "2026-04-30",
  },
  {
    id: "33",
    name: "Premium Bank Card",
    slug: "premium-bank-card",
    folder: "PremiumBankCard",
    fileName: "PremiumBankcard",
    category: "Cards",
    description: "A high-fidelity premium bank card UI component with a stunning multi-layer slope design and interactive toggle.",
    dependencies: [],
    props: [],
    tags: ["card", "bank", "premium", "banking", "finance", "interactive"],
    isNew: true,
    createdAt: "2026-04-30",
  },
  {
    id: "35",
    name: "Liquid Wave Text",
    slug: "liquid-wave-text",
    folder: "LiquidText",
    fileName: "LiquidText",
    category: "TextAnimations",
    description: "A liquid wave text distortion effect using GSAP and SVG feTurbulence.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"Liquid Wave"', description: "Text to display" },
      { name: "speed", type: "number", default: "4", description: "Animation duration in seconds" },
      { name: "amplitude", type: "number", default: "30", description: "Displacement map scale" },
      { name: "baseFreqX", type: "number", default: "0.01", description: "Base frequency X" },
      { name: "baseFreqY", type: "number", default: "0.015", description: "Base frequency Y" },
      { name: "targetFreqX", type: "number", default: "0.03", description: "Target frequency X" },
      { name: "targetFreqY", type: "number", default: "0.04", description: "Target frequency Y" },
      { name: "verticalSway", type: "number", default: "12", description: "Vertical sway amount in pixels" },
      { name: "fontSize", type: "string", default: '"clamp(4rem, 8vw, 130px)"', description: "CSS font size" },
      { name: "fontFamily", type: "string", default: '"system-ui, sans-serif"', description: "CSS font family" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "liquid", "wave", "gsap", "svg", "animation"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "36",
    name: "3D Flip Text",
    slug: "flip-text",
    folder: "FlipText",
    fileName: "FlipText",
    category: "TextAnimations",
    description: "A stunning 3D flip text animation where letters rotate into view individually using Framer Motion.",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"3D FLIP ENTRANCE"', description: "Text to display" },
      { name: "staggerDuration", type: "number", default: "0.05", description: "Delay between each letter's animation in seconds" },
      { name: "damping", type: "number", default: "12", description: "Spring damping (bounciness)" },
      { name: "stiffness", type: "number", default: "120", description: "Spring stiffness (speed)" },
      { name: "initialRotateY", type: "number", default: "90", description: "Initial Y-axis rotation in degrees" },
      { name: "initialZ", type: "number", default: "-300", description: "Initial Z-axis offset in pixels" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "flip", "3d", "framer-motion", "animation", "entrance"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "37",
    name: "Infinite Marquee",
    slug: "infinite-marquee",
    folder: "InfiniteMarquee",
    fileName: "InfiniteMarquee",
    category: "TextAnimations",
    description: "A smooth scrolling infinite marquee with layered parallax depth and scroll-linked velocity effects.",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"INFINITE PARALLAX MARQUEE — "', description: "Text to display in the marquee" },
      { name: "baseVelocity", type: "number", default: "-1", description: "Base speed and direction (negative is left)" },
      { name: "layers", type: "number", default: "1", description: "Number of depth layers" },
      { name: "fontSize", type: "string", default: '"clamp(3rem, 10vw, 8rem)"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "marquee", "infinite", "parallax", "scroll", "framer-motion"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "38",
    name: "Text Morph",
    slug: "text-morph",
    folder: "TextMorph",
    fileName: "TextMorph",
    category: "TextAnimations",
    description: "A fluid word-to-word shape shifting animation using Framer Motion's layoutId, scale, and crossfade blur effects.",
    dependencies: ["framer-motion"],
    props: [
      { name: "prefix", type: "string", default: "\"LET'S\"", description: "Static text before the morphing words" },
      { name: "text", type: "string", default: '"DREAM,BUILD,INNOVATE,SHAPE"', description: "Comma separated list of words to morph between" },
      { name: "suffix", type: "string", default: '"TOGETHER"', description: "Static text after the morphing words" },
      { name: "interval", type: "number", default: "1", description: "Duration each word stays on screen in seconds" },
      { name: "color", type: "string", default: '"#ffffff"', description: "Text color" },
      { name: "fontSize", type: "string", default: '"clamp(2rem, 4vw, 4rem)"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "morph", "framer-motion", "blur", "layoutId", "shape-shift"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "shine-text",
    name: "Shine Text",
    slug: "shine-text",
    folder: "ShineText",
    fileName: "ShineText",
    category: "TextAnimations",
    description: "A dynamic text component that creates a shine effect sliding from left to right.",
    dependencies: ["framer-motion", "motion/react"],
    props: [
      { name: "text", type: "string", default: '"Shine Effect"', description: "Text to display" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
      { name: "baseColor", type: "string", default: '"#78B54E"', description: "Base color of the text" },
      { name: "shineColor", type: "string", default: '"#ffffff"', description: "Color of the shine effect" },
      { name: "shineWidth", type: "number", default: "200", description: "Width of the shine effect in percentage" },
      { name: "speed", type: "number", default: "0.65", description: "Speed of the shine animation" },
      { name: "direction", type: "string", default: '"left-to-right"', description: "Direction of the shine ('left-to-right' | 'right-to-left')" },
    ],
    tags: ["text", "shine", "animation", "framer-motion", "motion", "effect"],
    isNew: true,
    createdAt: "2026-05-14",
  },
  {
    id: "39",
    name: "Scroll Reveal Text",
    slug: "scroll-reveal-text",
    folder: "ScrollRevealText",
    fileName: "ScrollRevealText",
    category: "TextAnimations",
    description: "A scroll-synced text scrub animation that reveals words using opacity, vertical translation, and clip-path mapped directly to scroll progress.",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Scroll to reveal this cinematic text scrub animation. It dynamically maps opacity, vertical position, and clip-path directly to your scroll progress for a buttery smooth reading experience."', description: "The text to reveal on scroll" },
      { name: "color", type: "string", default: '"#ffffff"', description: "Text color" },
      { name: "fontSize", type: "string", default: '"clamp(2rem, 5vw, 4rem)"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "scroll", "reveal", "scrub", "framer-motion", "clip-path"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "40",
    name: "Slide Up Text",
    slug: "slide-up-text",
    folder: "SlideUpText",
    fileName: "SlideUpText",
    category: "TextAnimations",
    description: "A smooth word-by-word slide up entrance animation with a subtle blur using Framer Motion spring physics.",
    dependencies: ["framer-motion"],
    props: [
      { name: "text", type: "string", default: '"Beautiful things happen when you least expect them"', description: "Text to animate" },
      { name: "staggerDuration", type: "number", default: "0.17", description: "Delay between each word in seconds" },
      { name: "yOffset", type: "number", default: "54", description: "Starting Y offset in pixels" },
      { name: "color", type: "string", default: '"#ffffff"', description: "Text color" },
      { name: "fontSize", type: "string", default: '"clamp(2rem, 5vw, 4rem)"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "slide-up", "entrance", "framer-motion", "stagger", "animation"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "41",
    name: "Text Roller",
    slug: "text-roller",
    folder: "TextRoller",
    fileName: "TextRoller",
    category: "TextAnimations",
    description: "A premium GSAP-powered infinite vertical text roller with 3D arc distortion, perspective depth, blur falloff, and arrow selection indicator. Inspired by iOS wheel pickers.",
    dependencies: ["gsap"],
    props: [
      { name: "words", type: "string", default: '"APPLICATIONS,ARCHITECTURE,PERFORMANCE,SCALABILITY,SECURITY,DEPLOYMENT,OPTIMIZATION,TESTING,APIs,INTEGRATION"', description: "Comma separated list of words to cycle through" },
      { name: "speed", type: "number", default: "1.2", description: "Seconds per word (lower = faster)" },
      { name: "curveStrength", type: "number", default: "100", description: "Horizontal arc curve intensity in pixels" },
      { name: "fontSize", type: "string", default: '"4rem"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "roller", "picker", "gsap", "3d", "infinite", "wheel"],
    isNew: true,
    createdAt: "2026-05-06",
  },
  {
    id: "42",
    name: "Magnetic Hover Text",
    slug: "magnetic-hover-text",
    folder: "MagneticHoverText",
    fileName: "MagneticHoverText",
    category: "TextAnimations",
    description: "Butter-smooth magnetic character hover effect using GSAP quickTo. Letters push away from the cursor based on proximity, creating a fluid, jank-free physical interaction.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"MAGNETIC HOVER"', description: "The text to display" },
      { name: "radius", type: "number", default: "120", description: "Magnetic field radius in pixels" },
      { name: "strength", type: "number", default: "50", description: "Maximum push distance in pixels" },
      { name: "fontSize", type: "string", default: '"clamp(3rem, 8vw, 6rem)"', description: "CSS font size" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "hover", "magnetic", "gsap", "quickTo", "interaction"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "44",
    name: "Rotating Text",
    slug: "rotating-text",
    folder: "RotatingText",
    fileName: "RotatingText",
    category: "TextAnimations",
    description: "An infinite rotating text wheel component with smooth vertical scroll, blur fade effects, and a fixed prefix text. Perfect for dynamically displaying services or hero headlines.",
    dependencies: ["gsap"],
    props: [
      { name: "fixedText", type: "string", default: '"WE DESIGN"', description: "The static prefix text" },
      { name: "words", type: "string[]", default: '["WEBSITES", "EXPERIENCES", "INTERFACES", "PRODUCTS", "SYSTEMS", "JOURNEYS", "SOLUTIONS", "BRANDS"]', description: "List of words to rotate through" },
      { name: "interval", type: "number", default: "2500", description: "Time between rotations in milliseconds" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "rotating", "scroller", "wheel", "animation", "gsap"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "43",
    name: "Hover Reveal Card",
    slug: "hover-reveal-card",
    folder: "HoverRevealCard",
    fileName: "HoverRevealCard",
    category: "Cards",
    description: "Premium 3D card reveal with smooth perspective and transform animations on hover.",
    dependencies: ["react", "gsap"],
    props: [
      { name: "title", type: "string", default: '"The Weeknd"', description: "Main card title" },
      { name: "subtitle", type: "string", default: '"STARBOY"', description: "Secondary card text" },
      { name: "description", type: "string", default: '"Experience the electric energy of Starboy, a cinematic and auditory masterpiece."', description: "Card description" },
      { name: "imageSrc", type: "string", default: '"https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=800&auto=format&fit=crop"', description: "Image URL for the card" },
      { name: "buttonText", type: "string", default: '"Play Now"', description: "Button label" },
      { name: "perspective", type: "number", default: "1000", description: "3D perspective strength" },
      { name: "hoverDelay", type: "number", default: "0", description: "Delay before hover animation starts" },
    ],
    tags: ["text", "hover", "card", "3d", "perspective", "transform"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "45",
    name: "Kinetic Split Text",
    slug: "kinetic-split-text",
    folder: "KineticSplitText",
    fileName: "KineticSplitText",
    category: "TextAnimations",
    description: "Oversized headline typography where characters animate independently with a cinematic staggered blur and depth reveal.",
    dependencies: ["gsap", "split-type"],
    props: [
      { name: "text", type: "string", default: '"KINETIC TYPOGRAPHY"', description: "Text to animate" },
      { name: "staggerDuration", type: "number", default: "0.04", description: "Delay between each character's animation" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Color of the text" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "kinetic", "split", "blur", "stagger", "gsap", "entrance", "reveal"],
    isNew: true,
    createdAt: "2026-05-07",
  }, {
    id: "46",
    name: "Curved Typography",
    slug: "curved-typography",
    folder: "CurvedTypography",
    fileName: "CurvedTypography",
    category: "TextAnimations",
    description: "Typography flowing along dynamic SVG curves, circles, and spirals with continuous slow motion and subtle path morphing.",
    dependencies: ["framer-motion", "gsap"],
    props: [
      { name: "text", type: "string", default: '"CREATIVE TECHNOLOGY · EXPERIMENTAL TYPOGRAPHY · WEB DEVELOPMENT · "', description: "Text to flow along the path" },
      { name: "type", type: "enum", default: '"wave"', description: "Path type: 'circle', 'wave', or 'spiral'" },
      { name: "speed", type: "number", default: "10", description: "Animation duration in seconds" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Color of the text" },
      { name: "fontSize", type: "number | string", default: "40", description: "Font size of the text" },
      { name: "fontWeight", type: "number | string", default: "800", description: "Font weight of the text" },
      { name: "letterSpacing", type: "number | string", default: '"2px"', description: "Letter spacing for the text" },
      { name: "showPath", type: "boolean", default: "true", description: "Toggle visibility of the guiding SVG path" },
      { name: "pathColor", type: "string", default: '"rgba(255, 255, 255, 0.05)"', description: "Color of the guiding SVG path" },
      { name: "morphSpeed", type: "number", default: "8", description: "Speed of the subtle shape morphing in seconds" },
    ],
    tags: ["text", "curved", "svg", "textPath", "framer-motion", "gsap", "flow", "spiral", "circle", "wave"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "47",
    name: "Glitch Text",
    slug: "glitch-text",
    folder: "GlitchText",
    fileName: "GlitchText",
    category: "TextAnimations",
    description: "Intense cyberpunk glitch typography featuring RGB channel separation, SVG displacement distortion, flickering text, and randomized jitter.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"CYBERPUNK"', description: "The text to display and glitch" },
      { name: "fontSize", type: "string", default: '"clamp(3rem, 10vw, 8rem)"', description: "Font size of the text" },
      { name: "fontWeight", type: "string", default: '"900"', description: "Font weight of the text" },
      { name: "fontFamily", type: "string", default: '"\'Inter\', system-ui, sans-serif"', description: "Font family of the text" },
      { name: "intensity", type: "number", default: "0.32", min: 0.1, max: 3, step: 0.1, description: "How intense the glitch effect is (multiplier)" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "glitch", "cyberpunk", "gsap", "svg", "distortion", "flicker", "jitter"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "48",
    name: "Physics Text",
    slug: "physics-text",
    folder: "PhysicsText",
    fileName: "PhysicsText",
    category: "TextAnimations",
    description: "Typography that behaves like physical objects with falling letters, bouncing words, and draggable gravity interactions powered by Matter.js.",
    dependencies: ["matter-js", "gsap"],
    props: [
      { name: "text", type: "string", default: '"DRAG ME PLAYFUL GRAVITY BOUNCE"', description: "The text to simulate" },
      { name: "splitMode", type: "enum", default: '"words"', description: "Split by 'words' or 'chars'" },
      { name: "fontSize", type: "string", default: '"clamp(2rem, 6vw, 5rem)"', description: "Font size of the text" },
      { name: "fontWeight", type: "string", default: '"900"', description: "Font weight of the text" },
      { name: "fontFamily", type: "string", default: '"\'Inter\', system-ui, sans-serif"', description: "Font family of the text" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Text color" },
      { name: "gravity", type: "number", default: "1", min: -2, max: 5, step: 0.1, description: "Gravity multiplier (negative for reverse gravity)" },
      { name: "bounciness", type: "number", default: "0.6", min: 0, max: 1.5, step: 0.1, description: "Bounciness (restitution) of the text" },
      { name: "friction", type: "number", default: "0.1", min: 0, max: 1, step: 0.05, description: "Friction of the bodies" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "physics", "matter-js", "gravity", "bounce", "interactive", "drag", "gsap", "svg"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "49",
    name: "3D Depth Text",
    slug: "depth-text",
    folder: "DepthText",
    fileName: "DepthText",
    category: "TextAnimations",
    description: "Fake 3D typography utilizing CSS perspective, layered parallax depth shadows, and smooth cinematic GSAP camera drift.",
    dependencies: ["gsap"],
    props: [
      { name: "text", type: "string", default: '"PARALLAX"', description: "The text to display" },
      { name: "layers", type: "number", default: "12", min: 1, max: 30, step: 1, description: "Number of text layers to simulate depth" },
      { name: "depth", type: "number", default: "12", min: 0, max: 50, step: 1, description: "Distance in pixels between each layer" },
      { name: "maxRotation", type: "number", default: "25", min: 0, max: 90, step: 1, description: "Maximum camera rotation angle in degrees" },
      { name: "fontSize", type: "string", default: '"clamp(4rem, 15vw, 12rem)"', description: "Font size" },
      { name: "fontWeight", type: "string", default: '"900"', description: "Font weight" },
      { name: "fontFamily", type: "string", default: '"\'Inter\', system-ui, sans-serif"', description: "Font family" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Color of the frontmost text" },
      { name: "shadowColor", type: "string", default: '"#3b82f6"', description: "Color of the trailing shadow layers" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "3d", "depth", "parallax", "perspective", "gsap", "camera", "layered"],
    createdAt: "2026-05-07",
  },
  {
    id: "50",
    name: "True 3D Text",
    slug: "true-3d-text",
    folder: "True3DText",
    fileName: "True3DText",
    category: "TextAnimations",
    description: "Authentic 3D geometry text rendering with bevels, cinematic chrome materials, interactive rotation, and post-processing glow (bloom).",
    dependencies: ["@react-three/fiber", "@react-three/drei", "@react-three/postprocessing", "three"],
    props: [
      { name: "text", type: "string", default: '"LEGIT"', description: "The text to render in 3D" },
      { name: "bevelThickness", type: "number", default: "0.1", min: 0, max: 0.5, step: 0.01, description: "How thick the bevel should be" },
      { name: "bevelSize", type: "number", default: "0.04", min: 0, max: 0.2, step: 0.01, description: "How far the bevel extends" },
      { name: "metalness", type: "number", default: "1", min: 0, max: 1, step: 0.1, description: "Metalness of the material" },
      { name: "roughness", type: "number", default: "0.15", min: 0, max: 1, step: 0.05, description: "Roughness of the material" },
      { name: "color", type: "string", default: '"#e2e8f0"', description: "Base color of the text" },
      { name: "glowIntensity", type: "number", default: "1.2", min: 0, max: 5, step: 0.1, description: "Intensity of the cinematic glow" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["text", "3d", "geometry", "chrome", "bevel", "threejs", "fiber", "bloom", "glow", "cinematic"],
    createdAt: "2026-05-07",
  },
  {
    id: "51",
    name: "Scroll Wave Gallery",
    slug: "scroll-wave-gallery",
    folder: "ScrollWaveGallery",
    fileName: "ScrollWaveGallery",
    category: "Cards",
    description: "An infinite looping image gallery that arranges cards in a smooth diagonal sine wave shape, deeply tied to scroll progress.",
    dependencies: ["framer-motion", "lenis"],
    props: [
      { name: "loops", type: "number", default: "3", min: 1, max: 10, step: 1, description: "How many times the gallery loops over the scroll distance" },
      { name: "waveAmplitude", type: "number", default: "25", min: 0, max: 100, step: 1, description: "Amplitude of the wave curvature in vh" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["scroll", "gallery", "wave", "infinite", "loop", "framer-motion", "lenis", "parallax"],
    isNew: true,
    createdAt: "2026-05-07",
  },
  {
    id: "52",
    name: "ASCII Motion Text",
    slug: "ascii-motion-text",
    folder: "AsciiMotionText",
    fileName: "AsciiMotionText",
    category: "TextAnimations",
    description: "An ultra-premium interactive ASCII particle typography system powered by GPGPU shaders and React Three Fiber. Features fluid cursor repulsion and cinematic post-processing.",
    dependencies: ["@react-three/fiber", "@react-three/drei", "@react-three/postprocessing", "three"],
    props: [
      { name: "text", type: "string", default: '"MOTION"', description: "Text to transform into ASCII particles" },
      { name: "fontSize", type: "number", default: "1.5", description: "Size of the text in world units" },
      { name: "density", type: "number", default: "128", description: "Number of particles along one axis (grid size)" },
      { name: "mouseRadius", type: "number", default: "0.5", min: 0, max: 5, step: 0.1, description: "Radius of cursor interaction" },
      { name: "mouseStrength", type: "number", default: "0.3", description: "Strength of cursor repulsion" },
      { name: "relaxation", type: "number", default: "0.06", description: "Speed at which particles return to original position" },
      { name: "damping", type: "number", default: "0.05", description: "Motion damping to prevent jitter" },
      { name: "noiseFreq", type: "number", default: "0", description: "Frequency of the noise turbulence" },
      { name: "noiseAmp", type: "number", default: "0", description: "Amplitude of the noise distortion" },
      { name: "asciiChars", type: "string", default: '" .:-=+*%#░▒▓█"', description: "Characters used for the ASCII mapping" },
    ],
    tags: ["text", "ascii", "gpgpu", "shaders", "particles", "interactive", "threejs", "r3f", "premium"],
    isNew: true,
    createdAt: "2026-05-08",
  },
  {
    id: "53",
    name: "Cinematic Stacked Card Reveal",
    slug: "stacked-card-reveal",
    folder: "StackedCardReveal",
    fileName: "StackedCardReveal",
    category: "Cards",
    description: "A premium, cinematic stacked card reveal layout with glassmorphism, dynamic glowing gradients, subtle film grain, and organic parallax depth on scroll.",
    dependencies: ["framer-motion", "react"],
    props: [
      { name: "containerHeight", type: "string", default: '"100vh"', description: "CSS height value for the scroll container" }
    ],
    tags: ["scroll", "cards", "framer-motion", "stacked", "cinematic", "premium"],
    isNew: true,
    createdAt: "2026-05-08",
  },


  {
    id: "54",
    name: "Cinematic Scroll",
    slug: "cinematic-scroll",
    folder: "CinematicScroll",
    fileName: "CinematicScroll",
    category: "Animations",
    description: "A premium scroll-driven cinematic experience with horizontal storytelling panels, dynamic blur, image masking, and giant typography.",
    dependencies: ["gsap", "framer-motion", "lenis"],
    props: [
      { name: "panels", type: "CinematicPanelProps[]", description: "Array of panel data (id, title, subtitle, image)" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["scroll", "cinematic", "horizontal", "gsap", "framer-motion", "lenis", "parallax"],
    isNew: true,
    createdAt: "2026-05-08",
  },
  {
    id: "61",
    name: "Curved Typography Gallery",
    slug: "curved-typography-gallery",
    folder: "CurvedTypographyGallery",
    fileName: "CurvedTypographyGallery",
    category: "Animations",
    description: "An experimental poster system gallery featuring curved typography, scroll-driven rotation, and dynamic perspective scaling.",
    dependencies: ["gsap", "framer-motion"],
    props: [
      { name: "items", type: "CurvedGalleryItem[]", description: "Array of cards (id, title, subtitle, image)" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" },
    ],
    tags: ["scroll", "curved", "typography", "gsap", "framer-motion", "gallery", "perspective"],
    isNew: true,
    createdAt: "2026-05-08",
  },
  {
    id: "64",
    name: "Infinite Image Marquee",
    slug: "infinite-image-marquee",
    folder: "InfiniteImageMarquee",
    fileName: "InfiniteImageMarquee",
    category: "Animations",
    description: "An endless flowing image ribbon with kinetic scroll-velocity skewing, dynamic motion blur, and a 3D perspective tilt.",
    dependencies: ["gsap", "lenis"],
    props: [
      { name: "rows", type: "MarqueeRow[]", description: "Array of rows containing image URLs and scroll speed" }
    ],
    tags: ["scroll", "marquee", "infinite", "gsap", "image", "perspective", "velocity"],
    isNew: true,
    createdAt: "2026-05-10",
  },
  {
    id: "65",
    name: "Editorial Storytelling",
    slug: "editorial-storytelling",
    folder: "EditorialStorytelling",
    fileName: "EditorialStorytelling",
    category: "Animations",
    description: "Cinematic pinned editorial sections with split text typography reveals, dynamic image scaling, and seamless crossfade transitions.",
    dependencies: ["gsap", "lenis", "split-type"],
    props: [
      { name: "chapters", type: "StoryChapter[]", description: "Array of chapters containing title, description, and image URL" }
    ],
    tags: ["scroll", "editorial", "storytelling", "gsap", "split-type", "cinematic", "image", "text"],
    isNew: true,
    createdAt: "2026-05-10",
  },
  {
    id: "66",
    name: "Cursor Image Trail",
    slug: "cursor-image-trail",
    folder: "CursorImageTrail",
    fileName: "CursorImageTrail",
    category: "Animations",
    description: "A snake-like stack of images that elegantly trails your cursor with smooth kinetic rotation and fluid physics.",
    dependencies: ["gsap"],
    props: [
      { name: "images", type: "string[]", description: "Array of image URLs to tile" },
      { name: "renderCount", type: "number", default: "15", description: "Total number of images in the trail train" }
    ],
    tags: ["cursor", "mouse", "trail", "gsap", "image", "kinetic"],
    isNew: true,
    createdAt: "2026-05-10",
  },
  {
    id: "67",
    name: "Orbit Gallery",
    slug: "orbit-gallery",
    folder: "OrbitGallery",
    fileName: "OrbitGallery",
    category: "Animations",
    description: "A space-themed community orbit component with rotating circular avatars that expand on hover to reveal details. Glowing stars stay behind the avatars flawlessly.",
    dependencies: ["gsap"],
    props: [
      { name: "rings", type: "OrbitRingData[]", description: "Array of orbit rings containing radius, speed, nodes, and stars" },
      { name: "titleLine1", type: "string", default: '"Join Our"', description: "First line of the central title" },
      { name: "titleLine2", type: "string", default: '"Community"', description: "Second line of the central title (highlighted)" },
      { name: "buttonText", type: "string", default: '"Join Us"', description: "Text for the central button" }
    ],
    tags: ["orbit", "circular", "space", "stars", "hover", "gsap", "team", "community"],
    isNew: true,
    createdAt: "2026-05-10",
  },
  {
    id: "68",
    name: "Magnetic Dock",
    slug: "magnetic-dock",
    folder: "MagneticDock",
    fileName: "MagneticDock",
    category: "Animations",
    description: "A macOS-style dock with magnetic 3D scaling, smooth physics, and interactive glow effects.",
    dependencies: ["gsap"],
    props: [],
    tags: ["macos", "dock", "magnetic", "gsap", "physics", "interactive"],
    isNew: true,
    createdAt: "2026-05-11",
  },
  {
    id: "70",
    name: "Ascii Text",
    slug: "ascii-text",
    folder: "AsciiText",
    fileName: "AsciiText",
    category: "TextAnimations",
    description: "ASCII text animation component.",
    dependencies: [],
    props: [
      { name: "text", type: "string", default: '"LEGIT"', description: "Text to render as ASCII" },
      { name: "hoverRadius", type: "number", default: "40", description: "Radius of the mouse hover effect" },
      { name: "fontSize", type: "number", default: "12", description: "Font size of the ASCII characters" },
      { name: "charWidth", type: "number", default: "8", description: "Width of each ASCII character cell" },
      { name: "charHeight", type: "number", default: "12", description: "Height of each ASCII character cell" },
      { name: "textColor", type: "string", default: '"#ffffff"', description: "Color of the ASCII text" },
      { name: "className", type: "string", default: '""', description: "Additional CSS classes" }
    ],
    tags: ["ascii", "text", "animation"],
    isNew: true,
    createdAt: "2026-05-11",
  },
  {
    id: "71",
    name: "Horizon Gradient",
    slug: "horizon-gradient",
    folder: "HorizonGradient",
    fileName: "HorizonGradient",
    category: "Backgrounds",
    description: "A cinematic celestial horizon gradient background with film grain.",
    dependencies: [],
    props: [],
    tags: ["horizon", "gradient", "space", "celestial", "background"],
    isNew: true,
    createdAt: "2026-05-11",
  },
  {
    id: "72",
    name: "Network Nodes",
    slug: "network-nodes",
    folder: "NetworkNodes",
    fileName: "NetworkNodes",
    category: "LegitComponents",
    description: "An interactive network component with animated particles traveling along curved paths between satellite nodes and a central hub.",
    dependencies: ["framer-motion"],
    props: [
      { name: "mainNodeIcon", type: "React.ReactNode", description: "Main central node icon/content" },
      { name: "nodes", type: "NodeItem[]", description: "Array of surrounding nodes with positions" },
      { name: "particleColor", type: "string", default: '"#ffffff"', description: "Color of the glowing particle" },
      { name: "lineColor", type: "string", default: '"rgba(255, 255, 255, 0.2)"', description: "Color of the connection lines" },
      { name: "particleSpeed", type: "number", default: "3", description: "Speed of the particles (duration in seconds)" },
    ],
    tags: ["network", "nodes", "particles", "svg", "framer-motion", "connections"],
    isNew: true,
    createdAt: "2026-05-15",
  },
  {
    id: "73",
    name: "Timeline Steps",
    slug: "timeline-steps",
    folder: "TimelineSteps",
    fileName: "TimelineSteps",
    category: "LegitComponents",
    description: "A premium vertical timeline component with scroll-linked progress and staggered 3D card reveals.",
    dependencies: ["framer-motion", "lucide-react"],
    props: [
      { name: "steps", type: "TimelineStep[]", description: "Array of step objects" },
      { name: "className", type: "string", description: "Optional CSS class" }
    ],
    tags: ["timeline", "steps", "scroll", "framer-motion", "cards", "vertical"],
    isNew: true,
    createdAt: "2026-05-15",
  },
  {
    id: "74",
    name: "Chromatic Gradient",
    slug: "chromatic-gradient",
    folder: "ChromaticGradient",
    fileName: "ChromaticGradient",
    category: "Backgrounds",
    description: "A lightweight, pure-CSS animated chromatic gradient background with soft floating blooms, film grain, and a cinematic Apple-event aesthetic.",
    dependencies: [],
    props: [
      { name: "className", type: "string", description: "Additional CSS class for the container", default: '""' },
      { name: "color1", type: "string", description: "Primary bloom colour", default: '"#6b21ff"' },
      { name: "color2", type: "string", description: "Secondary bloom colour", default: '"#0ea5e9"' },
      { name: "color3", type: "string", description: "Tertiary bloom colour", default: '"#06b6d4"' },
      { name: "color4", type: "string", description: "Ambient accent colour", default: '"#7c3aed"' },
      { name: "duration", type: "number", description: "Animation duration in seconds (higher = slower)", default: "20" },
      { name: "blurAmount", type: "number", description: "Bloom blur radius in vw units", default: "20" },
      { name: "blobSize", type: "number", description: "Bloom size in vw units", default: "45" },
      { name: "grain", type: "boolean", description: "Show subtle film-grain overlay", default: "true" },
      { name: "children", type: "React.ReactNode", description: "Content rendered above the gradient" }
    ],
    tags: ["background", "gradient", "chromatic", "css", "cinematic", "premium", "lightweight"],
    isNew: true,
    createdAt: "2026-05-15",
  },
  {
    id: "75",
    name: "Silk Gradient",
    slug: "silk-gradient",
    folder: "SilkGradient",
    fileName: "SilkGradient",
    category: "Backgrounds",
    description: "A smooth WebGL animated gradient using OGL — flowing aurora-like glows from top and bottom edges with zero noise.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", description: "Additional CSS class", default: '""' },
      { name: "background", type: "string", description: "Background void colour", default: '"#020617"' },
      { name: "colorTop", type: "string", description: "Top edge glow colour", default: '"#1e40af"' },
      { name: "colorBottom", type: "string", description: "Bottom edge glow colour", default: '"#0c4a6e"' },
      { name: "colorAccent", type: "string", description: "Centre accent colour", default: '"#38bdf8"' },
      { name: "speed", type: "number", description: "Animation speed multiplier", default: "1.41" },
      { name: "intensity", type: "number", description: "Glow brightness (0–1)", default: "0.68" },
      { name: "spread", type: "number", description: "How far glows spread from edges (0.2–1.0)", default: "0.65" },
      { name: "children", type: "React.ReactNode", description: "Content rendered above the gradient" }
    ],
    tags: ["background", "gradient", "webgl", "ogl", "smooth", "silk", "aurora", "cinematic"],
    isNew: true,
    createdAt: "2026-05-15",
  },
  {
    id: "77",
    name: "Dark Ambient Gradient",
    slug: "dark-ambient-gradient",
    folder: "DarkAmbientGradient",
    fileName: "DarkAmbientGradient",
    category: "Backgrounds",
    description: "A dark-mode animated gradient background using OGL with deep black base and flowing emerald, teal, navy, and cyan gradients drifting like underwater light. Features fbm noise, depth distortion, and caustic highlights.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", description: "Additional CSS class", default: '""' },
      { name: "background", type: "string", description: "Deep black base colour", default: '"#010008"' },
      { name: "color1", type: "string", description: "Primary wave colour", default: '"#7c3aed"' },
      { name: "color2", type: "string", description: "Secondary wave colour", default: '"#db2777"' },
      { name: "color3", type: "string", description: "Deep undercurrent colour", default: '"#2563eb"' },
      { name: "color4", type: "string", description: "Highlight caustic colour", default: '"#06b6d4"' },
      { name: "speed", type: "number", description: "Animation speed multiplier", default: "1.11" },
      { name: "intensity", type: "number", description: "Glow brightness (0–1)", default: "0.9" },
      { name: "distortion", type: "number", description: "UV warp depth distortion strength (0–1)", default: "0.5" },
      { name: "children", type: "React.ReactNode", description: "Content rendered above the gradient" }
    ],
    tags: ["background", "gradient", "webgl", "ogl", "dark", "ambient", "underwater", "emerald", "teal", "cinematic"],
    isNew: true,
    createdAt: "2026-05-16",
  },
  {
    id: "78",
    name: "Liquid Chrome Particles",
    slug: "liquid-chrome-particles",
    folder: "LiquidChrome",
    fileName: "LiquidChromeParticles",
    category: "Backgrounds",
    description: "An interactive, wave-like ocean of liquid chrome particles using React Three Fiber. Features cursor interaction and iridescent metallic shaders.",
    dependencies: ["@react-three/fiber", "@react-three/drei", "three"],
    props: [
      { name: "className", type: "string", description: "Additional CSS class", default: '""' },
      { name: "particleCount", type: "number", description: "Total number of particles", default: "40000" },
      { name: "baseColor", type: "string", description: "Deep metallic base colour", default: '"#05050a"' },
      { name: "highlightColor", type: "string", description: "Chrome reflection colour", default: '"#ffffff"' },
      { name: "glowColor", type: "string", description: "Cursor interaction glow colour", default: '"#6699ff"' },
      { name: "speed", type: "number", description: "Wave animation speed multiplier", default: "0.3" },
      { name: "particleSize", type: "number", description: "Base particle point size", default: "12.0" },
      { name: "background", type: "string", description: "Container background colour", default: '"#050505"' },
    ],
    tags: ["background", "webgl", "threejs", "particles", "chrome", "interactive", "cursor", "dark"],
    isNew: true,
    createdAt: "2026-05-16",
  },
  {
    id: "79",
    name: "Hyperspeed Light Tunnel",
    slug: "hyperspeed-light-tunnel",
    folder: "HyperspeedLightTunnel",
    fileName: "HyperspeedLightTunnel",
    category: "Backgrounds",
    description: "A futuristic OGL webgl shader creating a hyperspeed light tunnel with glowing neon rays converging to a focal point. Smooth cinematic motion blur and energy streaks.",
    dependencies: ["ogl"],
    props: [
      { name: "className", type: "string", description: "Additional CSS class", default: '""' },
      { name: "background", type: "string", description: "Deep background base colour", default: '"#05000a"' },
      { name: "coreColor", type: "string", description: "Central core and burst colour", default: '"#ffaa00"' },
      { name: "streakColor1", type: "string", description: "Primary energy streaks", default: '"#ff007f"' },
      { name: "streakColor2", type: "string", description: "Secondary energy streaks", default: '"#7000ff"' },
      { name: "streakColor3", type: "string", description: "Thin highlight streaks", default: '"#00f0ff"' },
      { name: "speed", type: "number", description: "Animation speed multiplier", default: "30" },
      { name: "density", type: "number", description: "Density of the light streaks", default: "30.0" },
      { name: "curve", type: "number", description: "Tunnel trumpet curve (1.0 to 3.0)", default: "1.5" },
      { name: "children", type: "React.ReactNode", description: "Content rendered above the background" }
    ],
    tags: ["background", "gradient", "webgl", "ogl", "scifi", "tunnel", "hyperspeed", "neon", "rays", "cinematic"],
    isNew: true,
    createdAt: "2026-05-16",
  },
  {
    id: "76",
    name: "Orbit Carousel",
    slug: "orbit-carousel",
    folder: "OrbitCarousel",
    fileName: "OrbitCarousel",
    category: "Animations",
    description: "A premium circular card gallery with high-fidelity motion. Features 2-round clockwise orbits with smooth reverse loops and stabilized upright cards.",
    dependencies: ["framer-motion"],
    props: [
      { name: "radius", type: "number", description: "Radius of the orbit", default: "180" },
      { name: "duration", type: "number", description: "Cycle duration in seconds", default: "15" },
      { name: "cardWidth", type: "number", description: "Width of cards", default: "120" },
      { name: "cardHeight", type: "number", description: "Height of cards", default: "160" },
      { name: "className", type: "string", description: "Additional CSS class", default: '""' }
    ],
    tags: ["animation", "carousel", "orbit", "circular", "framer-motion", "gallery", "premium"],
    isNew: true,
    createdAt: "2026-05-16",
  },
  
];
// ────────────────────────────────────────────────────
// Helper: look up a component by slug
// ────────────────────────────────────────────────────
export function getComponentMetaBySlug(slug: string): ComponentMeta | undefined {
  return defaultComponents.find((c) => c.slug === slug);
}
