// ════════════════════════════════════════════════════
// LegitUI — Preview Map (slug → dynamic import + weight)
// ════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/auto-register.ts
// Do not edit manually — run: npm run auto:register
//
// Weights:
//   light   — Pure CSS/JS, no heavy deps. Loads instantly.
//   medium  — GSAP or Framer Motion. Loads in 1–2 seconds.
//   heavy   — Three.js, OGL, or R3F. Loads in 2–4 seconds.
//   extreme — R3F + postprocessing, physics, or multiple heavy deps.
// ════════════════════════════════════════════════════

export type ComponentWeight = 'light' | 'medium' | 'heavy' | 'extreme';

export interface PreviewEntry {
  load: () => Promise<{ default: React.ComponentType<any> }>;
  weight: ComponentWeight;
}

export const PREVIEW_MAP: Record<string, PreviewEntry> = {
  // ── LIGHT — Pure CSS/JS, no heavy deps ──
  'animated-border': { load: () => import('@/ui-components/AnimatedBorder/AnimatedBorderUsage'), weight: 'light' },
  'ascii-text': { load: () => import('@/ui-components/AsciiText/AsciiTextUsage'), weight: 'light' },
  'aurora-background': { load: () => import('@/ui-components/AuroraBackground/AuroraBackgroundUsage'), weight: 'light' },
  'blur-cursor-text': { load: () => import('@/ui-components/BlurCursorText/BlurCursorTextUsage'), weight: 'light' },
  'chromatic-gradient': { load: () => import('@/ui-components/ChromaticGradient/ChromaticGradientUsage'), weight: 'light' },
  'floating-input': { load: () => import('@/ui-components/FloatingInput/FloatingInputUsage'), weight: 'light' },
  'glow-card': { load: () => import('@/ui-components/GlowCard/GlowCardUsage'), weight: 'light' },
  'halftone-eyes': { load: () => import('@/ui-components/HalftoneEyes/HalftoneEyesUsage'), weight: 'light' },
  'horizon-gradient': { load: () => import('@/ui-components/HorizonGradient/HorizonGradientUsage'), weight: 'light' },
  'magnetic-button': { load: () => import('@/ui-components/MagneticButton/MagneticButtonUsage'), weight: 'light' },
  'premium-bank-card': { load: () => import('@/ui-components/PremiumBankCard/PremiumBankCardUsage'), weight: 'light' },
  'pulse-loader': { load: () => import('@/ui-components/PulseLoader/PulseLoaderUsage'), weight: 'light' },
  'ripple-button': { load: () => import('@/ui-components/RippleButton/RippleButtonUsage'), weight: 'light' },
  'shimmer-button': { load: () => import('@/ui-components/ShimmerButton/ShimmerButtonUsage'), weight: 'light' },
  'signpost-navigation': { load: () => import('@/ui-components/SignpostNavigation/SignpostNavigationUsage'), weight: 'light' },
  'skeleton-loader': { load: () => import('@/ui-components/SkeletonLoader/SkeletonLoaderUsage'), weight: 'light' },
  'spinning-spiral': { load: () => import('@/ui-components/SpinningSpiral/SpinningSpiralUsage'), weight: 'light' },
  'spotlight-card': { load: () => import('@/ui-components/SpotlightCard/SpotlightCardUsage'), weight: 'light' },
  'tearable-cloth': { load: () => import('@/ui-components/TearableCloth/TearableClothUsage'), weight: 'light' },
  'typewriter-text': { load: () => import('@/ui-components/TypewriterText/TypewriterTextUsage'), weight: 'light' },
  'typewriter-text-new': { load: () => import('@/ui-components/TypewriterText/TypewriterTextUsage'), weight: 'light' },
  'violet-arc-background': { load: () => import('@/ui-components/VioletArcBackground/VioletArcBackgroundUsage'), weight: 'light' },

  // ── MEDIUM — GSAP or Framer Motion ──
  '3d-gallery': { load: () => import('@/ui-components/3DGallery/3DGalleryUsage'), weight: 'medium' },
  'animated-gradient-text': { load: () => import('@/ui-components/AnimatedGradient/AnimatedGradientUsage'), weight: 'medium' },
  'card-wheel-spread': { load: () => import('@/ui-components/CardWheelSpread/CardWheelSpreadUsage'), weight: 'medium' },
  'cinematic-scroll': { load: () => import('@/ui-components/CinematicScroll/CinematicScrollUsage'), weight: 'medium' },
  'cinematic-text': { load: () => import('@/ui-components/CinematicText/CinematicTextUsage'), weight: 'medium' },
  'cursor-image-trail': { load: () => import('@/ui-components/CursorImageTrail/CursorImageTrailUsage'), weight: 'medium' },
  'curved-typography': { load: () => import('@/ui-components/CurvedTypography/CurvedTypographyUsage'), weight: 'medium' },
  'curved-typography-gallery': { load: () => import('@/ui-components/CurvedTypographyGallery/CurvedTypographyGalleryUsage'), weight: 'medium' },
  'depth-text': { load: () => import('@/ui-components/DepthText/DepthTextUsage'), weight: 'medium' },
  'editorial-storytelling': { load: () => import('@/ui-components/EditorialStorytelling/EditorialStorytellingUsage'), weight: 'medium' },
  'expandable-product-cards': { load: () => import('@/ui-components/ExpandableProductCards/ExpandableProductCardsUsage'), weight: 'medium' },
  'expandable-task-card': { load: () => import('@/ui-components/ExpandableTaskCard/ExpandableTaskCard'), weight: 'medium' },
  'fanning-cards': { load: () => import('@/ui-components/FanningCards/FanningCardsUsage'), weight: 'medium' },
  'flip-text': { load: () => import('@/ui-components/FlipText/FlipTextUsage'), weight: 'medium' },
  'glitch-text': { load: () => import('@/ui-components/GlitchText/GlitchTextUsage'), weight: 'medium' },
  'hover-reveal-card': { load: () => import('@/ui-components/HoverRevealCard/HoverRevealCardUsage'), weight: 'medium' },
  'infinite-image-marquee': { load: () => import('@/ui-components/InfiniteImageMarquee/InfiniteImageMarqueeUsage'), weight: 'medium' },
  'infinite-marquee': { load: () => import('@/ui-components/InfiniteMarquee/InfiniteMarqueeUsage'), weight: 'medium' },
  'kinetic-split-text': { load: () => import('@/ui-components/KineticSplitText/KineticSplitTextUsage'), weight: 'medium' },
  'liquid-wave-text': { load: () => import('@/ui-components/LiquidText/LiquidTextUsage'), weight: 'medium' },
  'magnetic-dock': { load: () => import('@/ui-components/MagneticDock/MagneticDockUsage'), weight: 'medium' },
  'magnetic-hover-text': { load: () => import('@/ui-components/MagneticHoverText/MagneticHoverTextUsage'), weight: 'medium' },
  'network-nodes': { load: () => import('@/ui-components/NetworkNodes/NetworkNodesUsage'), weight: 'medium' },
  'numbers-count': { load: () => import('@/ui-components/NumbersCount/NumbersCountUsage'), weight: 'medium' },
  'orbit-carousel': { load: () => import('@/ui-components/OrbitCarousel/OrbitCarouselUsage'), weight: 'medium' },
  'orbit-gallery': { load: () => import('@/ui-components/OrbitGallery/OrbitGalleryUsage'), weight: 'medium' },
  'physics-text': { load: () => import('@/ui-components/PhysicsText/PhysicsTextUsage'), weight: 'medium' },
  'pixelify-text': { load: () => import('@/ui-components/PixelifyText/PixelifyText'), weight: 'medium' },
  'premium-3d-cursor': { load: () => import('@/ui-components/Premium3DCursor/Premium3DCursorUsage'), weight: 'medium' },
  'rotating-text': { load: () => import('@/ui-components/RotatingText/RotatingTextUsage'), weight: 'medium' },
  'scale-blur': { load: () => import('@/ui-components/ScaleBlur/ScaleBlurUsage'), weight: 'medium' },
  'scroll-circle-transition': { load: () => import('@/ui-components/ScrollCircleTransition/ScrollCircleTransitionUsage'), weight: 'medium' },
  'scroll-reveal-text': { load: () => import('@/ui-components/ScrollRevealText/ScrollRevealTextUsage'), weight: 'medium' },
  'scroll-snake-transition': { load: () => import('@/ui-components/ScrollSnakeTransition/ScrollSnakeTransitionUsage'), weight: 'medium' },
  'scroll-wave-gallery': { load: () => import('@/ui-components/ScrollWaveGallery/ScrollWaveGalleryUsage'), weight: 'medium' },
  'shine-text': { load: () => import('@/ui-components/ShineText/ShineTextUsage'), weight: 'medium' },
  'slide-up-text': { load: () => import('@/ui-components/SlideUpText/SlideUpTextUsage'), weight: 'medium' },
  'smooth-fade-up': { load: () => import('@/ui-components/SmoothFadeUp/SmoothFadeUpUsage'), weight: 'medium' },
  'stacked-card-reveal': { load: () => import('@/ui-components/StackedCardReveal/StackedCardRevealUsage'), weight: 'medium' },
  'staggered-word-slide': { load: () => import('@/ui-components/StaggeredWordSlide/StaggeredWordSlideUsage'), weight: 'medium' },
  'swipeable-card-stack': { load: () => import('@/ui-components/SwipeableCardStack/SwipeableCardStackUsage'), weight: 'medium' },
  'text-morph': { load: () => import('@/ui-components/TextMorph/TextMorphUsage'), weight: 'medium' },
  'text-reveal': { load: () => import('@/ui-components/TextReveal/TextRevealUsage'), weight: 'medium' },
  'text-roller': { load: () => import('@/ui-components/TextRoller/TextRollerUsage'), weight: 'medium' },
  'timeline-steps': { load: () => import('@/ui-components/TimelineSteps/TimelineStepsUsage'), weight: 'medium' },
  'typing-cursor': { load: () => import('@/ui-components/TypingCursor/TypingCursorUsage'), weight: 'medium' },

  // ── HEAVY — OGL / Three.js ──
  'dark-ambient-gradient': { load: () => import('@/ui-components/DarkAmbientGradient/DarkAmbientGradientUsage'), weight: 'heavy' },
  'fractal-haze': { load: () => import('@/ui-components/FractalHaze/FractalHaze'), weight: 'heavy' },
  'green-wave-ribbons': { load: () => import('@/ui-components/GreenWaveRibbons/GreenWaveRibbonsUsage'), weight: 'heavy' },
  'hyperspeed-light-tunnel': { load: () => import('@/ui-components/HyperspeedLightTunnel/HyperspeedLightTunnelUsage'), weight: 'heavy' },
  'liquid-nebula': { load: () => import('@/ui-components/LiquidNebula/LiquidNebula'), weight: 'heavy' },
  'mirror-capsules': { load: () => import('@/ui-components/MirrorCapsules/MirrorCapsuleUsage'), weight: 'heavy' },
  'neon-waves': { load: () => import('@/ui-components/NeonWaves/NeonWaves'), weight: 'heavy' },
  'particles-background': { load: () => import('@/ui-components/Particles/SpaceParticles'), weight: 'heavy' },
  'silk-gradient': { load: () => import('@/ui-components/SilkGradient/SilkGradientUsage'), weight: 'heavy' },
  'space-nebula-v1': { load: () => import('@/ui-components/SpaceNebulav1/SpaceNebulav1Usage'), weight: 'heavy' },
  'space-nebula-v2': { load: () => import('@/ui-components/SpaceNebulaV2/SpaceNebulaV2Usage'), weight: 'heavy' },

  // ── EXTREME — R3F + postprocessing / multiple heavy deps ──
  'ascii-motion-text': { load: () => import('@/ui-components/AsciiMotionText/AsciiMotionTextUsage'), weight: 'extreme' },
  'cinematic-black-hole': { load: () => import('@/ui-components/BlackHole/BlackHoleUsage'), weight: 'extreme' },
  'liquid-chrome-particles': { load: () => import('@/ui-components/LiquidChrome/LiquidChromeParticlesUsage'), weight: 'extreme' },
  'scroll-gallery': { load: () => import('@/ui-components/ScrollGallery/ScrollGalleryUsage'), weight: 'extreme' },
  'true-3d-text': { load: () => import('@/ui-components/True3DText/True3DTextUsage'), weight: 'extreme' },
};

export type ComponentSlug = keyof typeof PREVIEW_MAP;
