// ════════════════════════════════════════════════════
// LegitUI — Preview Map (slug → dynamic import)
// ════════════════════════════════════════════════════
// Maps every component slug to a dynamic import of its actual source component.
// Used by the preview route (/preview/[slug]) to render components natively.

export const PREVIEW_MAP: Record<string, () => Promise<{ default: React.ComponentType<any> }>> = {
  'shimmer-button': () => import('@/ui-components/ShimmerButton/ShimmerButtonUsage'),
  'glow-card': () => import('@/ui-components/GlowCard/GlowCardUsage'),
  'pulse-loader': () => import('@/ui-components/PulseLoader/PulseLoaderUsage'),
  'typewriter-text': () => import('@/ui-components/TypewriterText/TypewriterTextUsage'),
  'animated-border': () => import('@/ui-components/AnimatedBorder/AnimatedBorderUsage'),
  'floating-input': () => import('@/ui-components/FloatingInput/FloatingInputUsage'),
  'aurora-background': () => import('@/ui-components/AuroraBackground/AuroraBackgroundUsage'),
  'magnetic-button': () => import('@/ui-components/MagneticButton/MagneticButton'),
  'spotlight-card': () => import('@/ui-components/SpotlightCard/SpotlightCardUsage'),
  'skeleton-loader': () => import('@/ui-components/SkeletonLoader/SkeletonLoaderUsage'),
  'ripple-button': () => import('@/ui-components/RippleButton/RippleButton'),
  'particles-background': () => import('@/ui-components/Particles/SpaceParticles'),
  'neon-waves': () => import('@/ui-components/NeonWaves/NeonWaves'),
  'mirror-capsules': () => import('@/ui-components/MirrorCapsules/MirrorCapsule'),
  'fractal-haze': () => import('@/ui-components/FractalHaze/FractalHaze'),
  'liquid-nebula': () => import('@/ui-components/LiquidNebula/LiquidNebula'),
  'space-nebula-v1': () => import('@/ui-components/SpaceNebulav1/SpaceNebulav1'),
  'space-nebula-v2': () => import('@/ui-components/SpaceNebulaV2/SpaceNebulaV2'),
  'green-wave-ribbons': () => import('@/ui-components/GreenWaveRibbons/GreenWaveRibbonsUsage'),
  'cinematic-black-hole': () => import('@/ui-components/BlackHole/BlackHoleUsage'),
  '3d-gallery': () => import('@/ui-components/3DGallery/3DGalleryUsage'),
  'scroll-gallery': () => import('@/ui-components/ScrollGallery/ScrollGalleryUsage'),
  'text-reveal': () => import('@/ui-components/TextReveal/TextRevealUsage'),
  'smooth-fade-up': () => import('@/ui-components/SmoothFadeUp/SmoothFadeUpUsage'),
  'cinematic-text': () => import('@/ui-components/CinematicText/CinematicTextUsage'),
  'scale-blur': () => import('@/ui-components/ScaleBlur/ScaleBlurUsage'),
  'staggered-word-slide': () => import('@/ui-components/StaggeredWordSlide/StaggeredWordSlideUsage'),
  'typing-cursor': () => import('@/ui-components/TypingCursor/TypingCursorUsage'),
  'typewriter-text-new': () => import('@/ui-components/TypewriterText/TypewriterTextUsage'),
  'pixelify-text': () => import('@/ui-components/PixelifyText/PixelifyUsage'),
  'numbers-count': () => import('@/ui-components/NumbersCount/NumbersCountUsage'),
  'premium-bank-card': () => import('@/ui-components/PremiumBankCard/PremiumBankCardUsage'),
  'animated-gradient-text': () => import('@/ui-components/AnimatedGradient/AnimatedGradientUsage'),
  'liquid-wave-text': () => import('@/ui-components/LiquidText/LiquidTextUsage'),
  'flip-text': () => import('@/ui-components/FlipText/FlipTextUsage'),
  'infinite-marquee': () => import('@/ui-components/InfiniteMarquee/InfiniteMarqueeUsage'),
  'text-morph': () => import('@/ui-components/TextMorph/TextMorphUsage'),
  'scroll-reveal-text': () => import('@/ui-components/ScrollRevealText/ScrollRevealTextUsage'),
  'slide-up-text': () => import('@/ui-components/SlideUpText/SlideUpTextUsage'),
  'text-roller': () => import('@/ui-components/TextRoller/TextRollerUsage'),
  'magnetic-hover-text': () => import('@/ui-components/MagneticHoverText/MagneticHoverTextUsage'),
  'hover-reveal-card': () => import('@/ui-components/HoverRevealCard/HoverRevealCardUsage'),
  'rotating-text': () => import('@/ui-components/RotatingText/RotatingTextUsage'),
  'ascii-text': () => import('@/ui-components/AsciiText/AsciiTextUsage'),
  'kinetic-split-text': () => import('@/ui-components/KineticSplitText/KineticSplitTextUsage'),
  'curved-typography': () => import('@/ui-components/CurvedTypography/CurvedTypographyUsage'),
  'glitch-text': () => import('@/ui-components/GlitchText/GlitchTextUsage'),
  'physics-text': () => import('@/ui-components/PhysicsText/PhysicsTextUsage'),
  'depth-text': () => import('@/ui-components/DepthText/DepthTextUsage'),
  'true-3d-text': () => import('@/ui-components/True3DText/True3DTextUsage'),
  'scroll-wave-gallery': () => import('@/ui-components/ScrollWaveGallery/ScrollWaveGalleryUsage'),
  'ascii-motion-text': () => import('@/ui-components/AsciiMotionText/AsciiMotionTextUsage'),
  'stacked-card-reveal': () => import('@/ui-components/StackedCardReveal/StackedCardRevealUsage'),
  'cinematic-scroll': () => import('@/ui-components/CinematicScroll/CinematicScrollUsage'),
  'curved-typography-gallery': () => import('@/ui-components/CurvedTypographyGallery/CurvedTypographyGalleryUsage'),
  'infinite-image-marquee': () => import('@/ui-components/InfiniteImageMarquee/InfiniteImageMarqueeUsage'),
  'editorial-storytelling': () => import('@/ui-components/EditorialStorytelling/EditorialStorytellingUsage'),
  'cursor-image-trail': () => import('@/ui-components/CursorImageTrail/CursorImageTrailUsage'),
  'orbit-gallery': () => import('@/ui-components/OrbitGallery/OrbitGalleryUsage'),
  'magnetic-dock': () => import('@/ui-components/MagneticDock/MagneticDockUsage'),
  'horizon-gradient': () => import('@/ui-components/HorizonGradient/HorizonGradientUsage'),
} as const;

export type ComponentSlug = keyof typeof PREVIEW_MAP;
